services:
  - type: web
    name: taskflow-api
    runtime: node
    plan: free
    rootDir: Priti.Ahire_Task33/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://priti30-ai.github.io
